import { FormEvent, useState } from "react";
import { motion, useReducedMotion } from "framer-motion";
import { ArrowDown, ArrowRight, BriefcaseBusiness, Building2, CarFront, Check, ChevronDown, CircleAlert, FileCheck2, GraduationCap, Hotel, Menu, Phone, Plane, Quote, Send, SunMedium } from "lucide-react";
import { business } from "./data/business";

const iconMap = { plane: Plane, file: FileCheck2, school: GraduationCap, hotel: Hotel, car: CarFront, sun: SunMedium, briefcase: BriefcaseBusiness };
const navLinks = business.nav.map((label, index) => [label, ["#services", "#why", "#process", "#about", "#faq"][index]] as const);

function Eyebrow({ children, light = false }: { children: React.ReactNode; light?: boolean }) {
  return <p className={`mb-4 text-[11px] font-bold uppercase tracking-[0.24em] ${light ? "text-[#d3ad5e]" : "text-[#8c6a2b]"}`}>{children}</p>;
}

function WhatsAppAction({ compact = false }: { compact?: boolean }) {
  if (business.whatsappVerified) return <a href={business.whatsappHref} target="_blank" rel="noreferrer" className="cta-sweep inline-flex min-h-11 items-center justify-center gap-2 border border-[#d3ad5e] px-5 py-3 text-sm font-bold text-white hover:text-[#14372c]"><Send size={17} aria-hidden="true" /> WhatsApp</a>;
  return <span className={`inline-flex min-h-11 items-center justify-center gap-2 border border-white/25 px-4 py-3 text-xs font-semibold text-white/65 ${compact ? "" : "w-full sm:w-auto"}`} title="Demo preview: activate after the business confirms WhatsApp ownership"><CircleAlert size={16} aria-hidden="true" /> {business.hero.whatsappPending}</span>;
}

function Reveal({ children, className = "", id }: { children: React.ReactNode; className?: string; id?: string }) {
  const reduceMotion = useReducedMotion();
  return <motion.section id={id} className={className} initial={reduceMotion ? false : { opacity: 0, y: 24 }} whileInView={reduceMotion ? undefined : { opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.12 }} transition={{ duration: 0.58, ease: [0.22, 1, 0.36, 1] }}>{children}</motion.section>;
}

function Header() {
  const [open, setOpen] = useState(false);
  return <header className="absolute inset-x-0 top-0 z-30 border-b border-white/20 text-white"><div className="mx-auto flex min-h-20 max-w-7xl items-center justify-between px-5 sm:px-8"><a href="#top" className="font-display text-2xl font-bold tracking-tight" aria-label={`${business.name} home`}>Al-Baraq <span className="text-[#d3ad5e]">Travels</span></a><nav className="hidden items-center gap-6 lg:flex" aria-label="Main navigation">{navLinks.map(([label, href]) => <a key={href} href={href} className="flex min-h-11 items-center text-xs font-semibold text-white/85 hover:text-[#d3ad5e]">{label}</a>)}</nav><div className="hidden items-center gap-3 sm:flex"><a href={business.phoneHref} className="inline-flex min-h-11 items-center gap-2 px-2 text-sm font-bold hover:text-[#d3ad5e]"><Phone size={17} aria-hidden="true" /> {business.phoneDisplay}</a><WhatsAppAction compact /></div><button type="button" className="grid min-h-11 min-w-11 place-items-center sm:hidden" aria-expanded={open} aria-controls="mobile-nav" aria-label="Toggle navigation" onClick={() => setOpen((value) => !value)}><Menu aria-hidden="true" /></button></div>{open && <nav id="mobile-nav" className="border-t border-white/15 bg-[#14372c] px-5 py-4 sm:hidden" aria-label="Mobile navigation">{navLinks.map(([label, href]) => <a key={href} href={href} onClick={() => setOpen(false)} className="flex min-h-11 items-center border-b border-white/10 text-sm font-semibold">{label}</a>)}<a href={business.phoneHref} className="mt-3 flex min-h-11 items-center gap-2 font-bold text-[#d3ad5e]"><Phone size={17} aria-hidden="true" /> {business.phoneDisplay}</a></nav>}</header>;
}

function Hero() {
  const reduceMotion = useReducedMotion();
  return <section id="top" className="relative flex min-h-[760px] items-end overflow-hidden bg-[#14372c] text-white sm:min-h-[820px] lg:min-h-screen"><motion.img src={business.hero.image} alt={business.hero.imageAlt} fetchPriority="high" decoding="async" className="absolute inset-0 h-full w-full object-cover object-[64%_center]" initial={reduceMotion ? false : { scale: 1.06 }} animate={reduceMotion ? undefined : { scale: 1 }} transition={{ duration: 1.4, ease: [0.22, 1, 0.36, 1] }} /><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(9,30,24,.9)_0%,rgba(9,30,24,.7)_46%,rgba(9,30,24,.15)_100%)]" /><div className="absolute inset-0 bg-[linear-gradient(0deg,rgba(9,30,24,.72)_0%,transparent_48%)]" /><Header /><motion.div className="relative z-10 mx-auto w-full max-w-7xl px-5 pb-16 pt-36 sm:px-8 sm:pb-20 lg:pb-24" initial={reduceMotion ? false : { opacity: 0, y: 24 }} animate={reduceMotion ? undefined : { opacity: 1, y: 0 }} transition={{ duration: 0.72, delay: 0.15 }}><div className="max-w-3xl"><p className="mb-5 text-[11px] font-bold uppercase tracking-[0.24em] text-[#e5c77f]">{business.hero.eyebrow}</p><p className="font-display text-4xl font-bold leading-none text-[#e5c77f] sm:text-6xl">{business.name}</p><h1 className="font-display mt-3 max-w-2xl text-5xl font-semibold leading-[0.92] tracking-[-0.035em] sm:text-7xl lg:text-[6.4rem]">{business.hero.headline}</h1><p className="mt-6 max-w-xl text-base leading-7 text-white/80 sm:text-lg">{business.hero.supporting}</p><div className="mt-8 flex flex-col gap-3 sm:flex-row sm:items-center"><a href="#services" className="cta-sweep inline-flex min-h-12 items-center justify-center gap-2 bg-[#f7f2e8] px-6 py-3 text-sm font-bold text-[#14372c]">{business.hero.primaryCta} <ArrowDown size={17} aria-hidden="true" /></a><a href={business.phoneHref} className="cta-sweep inline-flex min-h-12 items-center justify-center gap-2 border border-white/60 px-6 py-3 text-sm font-bold text-white hover:text-[#14372c]"><Phone size={17} aria-hidden="true" /> {business.hero.phoneCta}</a><WhatsAppAction /></div></div></motion.div><div className="absolute bottom-0 right-0 hidden border-l border-t border-white/20 bg-[#14372c]/75 px-6 py-4 text-[10px] uppercase tracking-[0.2em] text-white/65 backdrop-blur-sm sm:block">{business.demoLabel}</div></section>;
}

function TrustBar() {
  return <aside className="bg-[#0d2a22] text-white" aria-label="Trust summary"><div className="mx-auto grid max-w-7xl gap-5 px-5 py-8 sm:px-8 lg:grid-cols-[1.1fr_1fr_1fr] lg:items-center"><p className="font-display text-2xl font-semibold text-[#e5c77f]">{business.trust.heading}</p><div className="text-sm leading-6 text-white/75"><p>{business.trust.reviewLine}</p><p>{business.trust.ratingLine}</p></div><p className="text-sm leading-6 text-white/75 lg:text-right">{business.trust.note}</p></div></aside>;
}

function Services({ onChoose }: { onChoose: (service: string) => void }) {
  return <Reveal id="services" className="scroll-mt-10 bg-[#f7f2e8] px-5 py-20 sm:px-8 lg:py-28"><div className="mx-auto max-w-7xl"><div className="grid gap-6 lg:grid-cols-2 lg:items-end"><div><Eyebrow>{business.serviceOverview.eyebrow}</Eyebrow><h2 className="font-display max-w-2xl text-4xl font-semibold leading-none tracking-tight sm:text-6xl">{business.serviceOverview.heading}</h2></div><p className="max-w-xl text-base leading-7 text-[#4e635c] lg:justify-self-end">{business.serviceOverview.intro}</p></div><div className="mt-14 border-t border-[#14372c]/20">{business.services.map((service, index) => { const Icon = iconMap[service.icon]; return <button key={service.title} type="button" onClick={() => onChoose(service.title)} className="group grid min-h-24 w-full grid-cols-[42px_1fr_auto] items-center gap-3 border-b border-[#14372c]/20 py-5 text-left transition-colors hover:bg-[#eee6d6] sm:grid-cols-[70px_1fr_1fr_auto]"><span className="text-xs font-bold text-[#8c6a2b]">0{index + 1}</span><span className="flex items-center gap-3 font-display text-2xl font-semibold sm:text-3xl"><Icon size={22} strokeWidth={1.5} aria-hidden="true" /> {service.title}</span><span className="hidden text-sm leading-6 text-[#61736d] sm:block">{service.detail}</span><ArrowRight className="transition-transform group-hover:translate-x-1" size={20} aria-hidden="true" /></button>; })}</div></div></Reveal>;
}

function Why() {
  return <Reveal id="why" className="scroll-mt-8 bg-[#14372c] px-5 py-20 text-white sm:px-8 lg:py-28"><div className="edge-lit mx-auto grid max-w-7xl gap-12 px-6 py-10 sm:px-10 sm:py-14 lg:grid-cols-[.8fr_1.2fr] lg:gap-24 lg:px-16 lg:py-20"><div><Eyebrow light>{business.why.eyebrow}</Eyebrow><h2 className="font-display text-4xl font-semibold leading-none sm:text-6xl">{business.why.heading}</h2><p className="mt-6 max-w-md leading-7 text-white/70">{business.why.body}</p></div><div className="border-t border-white/20">{business.why.points.map(([title, body], index) => <div key={title} className="grid gap-3 border-b border-white/20 py-7 sm:grid-cols-[44px_1fr]"><span className="font-display text-2xl text-[#d3ad5e]">{index + 1}</span><div><h3 className="text-base font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-white/65">{body}</p></div></div>)}</div></div></Reveal>;
}

function Explorer({ onChoose }: { onChoose: (service: string) => void }) {
  const [selected, setSelected] = useState<string>(business.services[0].title);
  return <Reveal className="bg-[#eee6d6] px-5 py-20 sm:px-8 lg:py-28"><div className="mx-auto max-w-7xl"><Eyebrow>{business.explorer.eyebrow}</Eyebrow><div className="grid gap-10 lg:grid-cols-[1fr_.8fr] lg:items-end"><h2 className="font-display text-5xl font-semibold leading-none sm:text-7xl">{business.explorer.heading}</h2><div><label htmlFor="service-explorer" className="mb-3 block text-sm font-semibold">{business.explorer.prompt}</label><div className="flex flex-col gap-3 sm:flex-row"><select id="service-explorer" value={selected} onChange={(e) => setSelected(e.target.value)} className="min-h-12 flex-1 border border-[#14372c]/30 bg-transparent px-4 text-sm">{business.services.map((item) => <option key={item.title}>{item.title}</option>)}</select><button type="button" onClick={() => onChoose(selected)} className="cta-sweep min-h-12 bg-[#14372c] px-6 text-sm font-bold text-white hover:text-[#14372c]">{business.explorer.action}</button></div></div></div></div></Reveal>;
}

function Process() {
  return <Reveal id="process" className="scroll-mt-8 bg-[#f7f2e8] px-5 py-20 sm:px-8 lg:py-28"><div className="mx-auto max-w-7xl"><Eyebrow>{business.process.eyebrow}</Eyebrow><h2 className="font-display max-w-4xl text-4xl font-semibold leading-none sm:text-6xl">{business.process.heading}</h2><div className="mt-14 grid border-l border-t border-[#14372c]/20 sm:grid-cols-2 lg:grid-cols-4">{business.process.steps.map(([number, title, body]) => <div key={number} className="min-h-64 border-b border-r border-[#14372c]/20 p-6"><span className="font-display text-3xl text-[#8c6a2b]">{number}</span><h3 className="mt-12 text-lg font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-[#61736d]">{body}</p></div>)}</div><p className="mt-5 text-xs font-semibold uppercase tracking-wider text-[#8c6a2b]">{business.process.note}</p></div></Reveal>;
}

function PhotoPlaceholder() {
  return <div className="edge-lit grid min-h-[380px] place-items-center bg-[#0d2a22] p-8 text-center text-white" role="img" aria-label="Owner photo placeholder"><div><Building2 className="mx-auto text-[#d3ad5e]" size={42} strokeWidth={1.2} aria-hidden="true" /><p className="font-display mt-5 text-3xl font-semibold">{business.about.placeholderTitle}</p><p className="mt-4 text-xs font-bold uppercase tracking-[.18em] text-[#d3ad5e]">[COLLECT FROM OWNER]</p><p className="mt-4 text-sm text-white/60">{business.about.placeholderSpec}</p><p className="mx-auto mt-2 max-w-sm text-xs leading-5 text-white/50">{business.about.placeholderSource}</p></div></div>;
}

function About() {
  return <Reveal id="about" className="scroll-mt-8 bg-[#d9cdb7] px-5 py-20 sm:px-8 lg:py-28"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-2 lg:items-center"><PhotoPlaceholder /><div className="lg:pl-10"><Eyebrow>{business.about.eyebrow}</Eyebrow><h2 className="font-display text-4xl font-semibold leading-none sm:text-6xl">{business.about.heading}</h2><p className="mt-6 leading-7 text-[#40574f]">{business.about.body}</p><a href={business.phoneHref} className="cta-sweep mt-8 inline-flex min-h-12 items-center gap-2 bg-[#14372c] px-6 text-sm font-bold text-white hover:text-[#14372c]"><Phone size={17} aria-hidden="true" /> {business.hero.phoneCta}</a></div></div></Reveal>;
}

function Assistance() {
  return <Reveal className="bg-[#14372c] px-5 py-20 text-white sm:px-8 lg:py-28"><div className="edge-lit mx-auto max-w-7xl px-6 py-12 sm:px-12 lg:px-20 lg:py-20"><Eyebrow light>{business.assistance.eyebrow}</Eyebrow><div className="grid gap-8 lg:grid-cols-[1.1fr_.9fr]"><h2 className="font-display text-4xl font-semibold leading-none sm:text-6xl">{business.assistance.heading}</h2><div><p className="leading-7 text-white/70">{business.assistance.body}</p><p className="mt-7 border-l-2 border-[#d3ad5e] pl-5 text-sm font-semibold leading-6 text-[#e5c77f]">{business.assistance.disclaimer}</p></div></div></div></Reveal>;
}

function Destinations() {
  return <Reveal className="bg-[#f7f2e8] px-5 py-20 sm:px-8 lg:py-28"><div className="mx-auto max-w-7xl"><Eyebrow>{business.destinations.eyebrow}</Eyebrow><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><h2 className="font-display text-4xl font-semibold leading-none sm:text-6xl">{business.destinations.heading}</h2><p className="max-w-md text-sm leading-6 text-[#61736d]">{business.destinations.intro}</p></div><div className="mt-12 grid gap-5 lg:grid-cols-2">{business.destinations.items.map((item) => <figure key={item.name} className="group relative min-h-[420px] overflow-hidden"><img src={item.image} alt={item.alt} loading="lazy" decoding="async" className="absolute inset-0 h-full w-full object-cover transition-transform duration-700 group-hover:scale-[1.03]" /><div className="absolute inset-0 bg-gradient-to-t from-[#0d2a22]/90 via-transparent to-transparent" /><figcaption className="absolute inset-x-0 bottom-0 p-6 text-white sm:p-8"><h3 className="font-display text-4xl font-semibold">{item.name}</h3><p className="mt-2 text-sm text-white/75">{item.line}</p><p className="mt-4 text-[10px] uppercase tracking-wider text-white/45">{item.credit}</p></figcaption></figure>)}</div></div></Reveal>;
}

function Reviews() {
  return <Reveal className="bg-[#eee6d6] px-5 py-20 sm:px-8 lg:py-28"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><Eyebrow>{business.reviews.eyebrow}</Eyebrow><Quote size={52} strokeWidth={1} className="text-[#8c6a2b]" aria-hidden="true" /></div><div><h2 className="font-display text-4xl font-semibold leading-none sm:text-6xl">{business.reviews.heading}</h2><p className="mt-6 max-w-2xl leading-7 text-[#4e635c]">{business.reviews.body}</p><div className="mt-8 border border-dashed border-[#8c6a2b]/60 p-5 text-sm font-semibold text-[#8c6a2b]">{business.reviews.slot}</div></div></div></Reveal>;
}

function FAQ() {
  return <Reveal id="faq" className="scroll-mt-8 bg-[#f7f2e8] px-5 py-20 sm:px-8 lg:py-28"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><Eyebrow>{business.faq.eyebrow}</Eyebrow><h2 className="font-display text-4xl font-semibold leading-none sm:text-6xl">{business.faq.heading}</h2></div><div className="border-t border-[#14372c]/20">{business.faq.items.map(([question, answer]) => <details key={question} className="group border-b border-[#14372c]/20"><summary className="flex min-h-16 cursor-pointer list-none items-center justify-between gap-4 py-4 font-bold"><span>{question}</span><ChevronDown className="shrink-0 transition-transform group-open:rotate-180" size={19} aria-hidden="true" /></summary><p className="pb-6 pr-8 text-sm leading-6 text-[#61736d]">{answer}</p></details>)}</div></div></Reveal>;
}

function InquiryForm({ selectedService, setSelectedService }: { selectedService: string; setSelectedService: (service: string) => void }) {
  const [status, setStatus] = useState<"idle" | "success" | "error">("idle");
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; if (!form.checkValidity()) { setStatus("error"); form.reportValidity(); return; } setStatus("success"); }
  const field = "min-h-12 w-full border border-white/25 bg-white/5 px-4 text-sm text-white placeholder:text-white/40 focus:border-[#d3ad5e]";
  return <form onSubmit={submit} noValidate className="edge-lit p-6 sm:p-8"><h3 className="font-display text-3xl font-semibold">{business.form.heading}</h3><p className="mt-3 text-xs leading-5 text-white/55">{business.form.note}</p><div className="mt-7 grid gap-5 sm:grid-cols-2"><label className="text-xs font-bold uppercase tracking-wider">{business.form.labels.name}<input required name="name" autoComplete="name" placeholder={business.form.placeholders.name} className={`${field} mt-2`} /></label><label className="text-xs font-bold uppercase tracking-wider">{business.form.labels.phone}<input required name="phone" type="tel" autoComplete="tel" placeholder={business.form.placeholders.phone} className={`${field} mt-2`} /></label></div><label className="mt-5 block text-xs font-bold uppercase tracking-wider">{business.form.labels.service}<select required name="service" value={selectedService} onChange={(e) => setSelectedService(e.target.value)} className={`${field} mt-2`}><option value="" className="text-[#14372c]">Select a service</option>{business.services.map((service) => <option key={service.title} className="text-[#14372c]">{service.title}</option>)}</select></label><label className="mt-5 block text-xs font-bold uppercase tracking-wider">{business.form.labels.message}<textarea required name="message" rows={4} placeholder={business.form.placeholders.message} className={`${field} mt-2 py-3`} /></label><button type="submit" className="cta-sweep mt-5 inline-flex min-h-12 w-full items-center justify-center gap-2 bg-[#f7f2e8] px-6 text-sm font-bold text-[#14372c]"><Send size={17} aria-hidden="true" /> {business.form.submit}</button><div aria-live="polite">{status === "success" && <p className="mt-5 flex gap-2 text-sm leading-6 text-[#e5c77f]"><Check className="mt-1 shrink-0" size={16} />{business.form.success}</p>}{status === "error" && <p className="mt-5 flex gap-2 text-sm text-[#f3c6b7]"><CircleAlert className="shrink-0" size={16} />{business.form.error}</p>}</div></form>;
}

function FinalCta({ selectedService, setSelectedService }: { selectedService: string; setSelectedService: (service: string) => void }) {
  return <Reveal className="bg-[#0d2a22] px-5 py-20 text-white sm:px-8 lg:py-28"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-[.8fr_1.2fr] lg:items-start"><div><Eyebrow light>{business.finalCta.eyebrow}</Eyebrow><h2 className="font-display text-5xl font-semibold leading-none sm:text-7xl">{business.finalCta.heading}</h2><p className="mt-6 max-w-md leading-7 text-white/65">{business.finalCta.body}</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><a href={business.phoneHref} className="cta-sweep inline-flex min-h-12 items-center justify-center gap-2 border border-[#d3ad5e] px-5 text-sm font-bold hover:text-[#14372c]"><Phone size={17} /> {business.phoneDisplay}</a><WhatsAppAction /></div></div><InquiryForm selectedService={selectedService} setSelectedService={setSelectedService} /></div></Reveal>;
}

function Footer() {
  return <footer className="border-t border-white/10 bg-[#0d2a22] px-5 py-10 text-white sm:px-8"><div className="mx-auto grid max-w-7xl gap-8 sm:grid-cols-2 lg:grid-cols-[1.2fr_1fr_1fr]"><div><p className="font-display text-3xl font-bold">{business.name}</p><p className="mt-2 text-sm text-white/55">{business.location}, Nigeria</p><a href={business.phoneHref} className="mt-3 inline-flex min-h-11 items-center text-sm font-semibold text-[#e5c77f]">{business.phoneDisplay}</a></div><div className="text-xs leading-6 text-white/50"><p>{business.footer.note}</p><p>{business.footer.privacy}</p><p>{business.footer.pending}</p></div><div className="flex items-start gap-2 lg:justify-end"><a href={business.instagram} target="_blank" rel="noreferrer" aria-label="Instagram - verify profile" className="grid min-h-11 min-w-11 place-items-center border border-white/20 text-xs font-bold hover:text-[#d3ad5e]">IG</a><a href={business.linkedin} target="_blank" rel="noreferrer" aria-label="LinkedIn - verify profile" className="grid min-h-11 min-w-11 place-items-center border border-white/20 text-xs font-bold hover:text-[#d3ad5e]">in</a><a href={business.facebook} target="_blank" rel="noreferrer" aria-label="Facebook - verify profile" className="grid min-h-11 min-w-11 place-items-center border border-white/20 text-xs font-bold hover:text-[#d3ad5e]">f</a></div></div></footer>;
}

export default function App() {
  const [selectedService, setSelectedService] = useState("");
  function chooseService(service: string) { setSelectedService(service); document.querySelector("form")?.scrollIntoView({ behavior: "smooth", block: "center" }); }
  return <div className="overflow-hidden"><a href="#main" className="fixed left-3 top-3 z-50 -translate-y-24 bg-[#f7f2e8] px-4 py-3 font-bold text-[#14372c] focus:translate-y-0">Skip to content</a><Hero /><TrustBar /><main id="main"><Services onChoose={chooseService} /><Why /><Explorer onChoose={chooseService} /><Process /><About /><Assistance /><Destinations /><Reviews /><FAQ /><FinalCta selectedService={selectedService} setSelectedService={setSelectedService} /></main><Footer /></div>;
}
